### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#437]
Can you please translate JEI into your language?

The language files are here:
https://github.com/mezz/JustEnoughItems/tree/1.10/src/main/resources/assets/jei/lang

Missing Language files:
language_file.lang contributors #PRs
- [x] ar_SA.lang EZtouch #515
- [x] bg_BG.lang sokratis12GR #406
- [x] cs_CZ.lang Astra3 #452
- [x] de_DE.lang Vexatos wlhlm copyyy mankra #87 #481
- [x] el_GR.lang ELChris414 #516
- [x] en_AU.lang AtomicBlom  #510
- [ ] en_PT.lang
- [x] en_US.lang 
- [x] es_ES.lang xlicer #400 
- [x] fi_FI.lang Juuxel #132
- [x] fr_FR.lang Jorys-Paulin #268
- [x] he_IL.lang tomaviv57 #524
- [ ] hu_HU.lang
- [x] it_IT.lang zabi94 #512
- [x] ja_JP.lang CrafterKina #441
- [x] ko_KR.lang anesin1109 #522
- [ ] lb_LU.lang
- [x] lt_LT.lang zygimantus #636
- [ ] lol_US.lang
- [x] nb_NO.lang kimfy #269 
- [ ] nl_NL.lang
- [x] pl_PL.lang maciekmm marcin212 #514
- [x] pt_BR.lang DaDodger #1229 #1228 #1220
- [x] ru_RU.lang xMrVizzy Adaptivity #442
- [x] sv_SE.lang Regnander #440
- [x] uk_UA.lang Coolboy21 #605
- [x] zh_CN.lang 3TUSK crafteverywhere #425
- [x] zh_TW.lang HeartyYF #447

Thank you!

**Comment by Madis0** [comment]
Sorry, not interested in translating things I don't use.

**Comment by mezz** [comment]
Understood, sorry to bother you.

**Comment by Astra3** [comment]
I never use this mod, but it doesn't look bad so I could look at that mod in game and after that if I want, I'll translate it.
EDIT: I translated it now, but I cannot release my translate because of your mod.
My language using symbols like as ě, š, č, ř, ž, ý, á, í,... which Minecraft supporting but your mod not. It shows question marks. I know I can make this translate without these symbols but It'll be better with them.

**Comment by mezz** [comment]
The mod should have no problem with those symbols. 
Go ahead with the correct translation, and I can fix any bugs after.

**Comment by HeartyYF** [comment]
Have pulled the request.I wonder why tou choose me :) But I'm very glad to offer help.

**Comment by mezz** [comment]
Round 2:

Can you please translate JEI into your language?

The language files are here:
https://github.com/mezz/JustEnoughItems/tree/1.10/src/main/resources/assets/jei/lang

ar_SA.lang @EZtouch
el_GR.lang @ELChris414
en_AU.lang @AtomicBlom
en_PT.lang @davdes15
he_IL.lang @tomaviv57
it_IT.lang @zabi94
ko_KR.lang (needs update) @anesin1109 
lol_US.lang @343Modding
nl_NL.lang @heldplayer
pl_PL.lang @Matrix89 @maciekmm
pt_BR.lang @Susjin
uk_UA.lang @Sfaxx

**Comment by zabi94** [comment]
Sure, I'll do it tomorrow, as soon as I can

**Comment by Mipsters** [comment]
I'll love to!
I just need a bit context to a few of the sentences because i don't use
this mod
And i do not know how to use the percent thingies...

If anyone would help me with those ill do it with pleasure!

**Comment by mezz** [comment]
I'm happy to help with any specific questions you have. 
Just make a PR with the parts you understand well, and you can ask about anything you are missing there.

**Comment by Mipsters** [comment]
Great! Ill start working on it tommorow

**Comment by davdes15** [comment]
I can help you translate the mod into Spanish if you want.

**Comment by mezz** [comment]
Thanks, there is already an es_ES file so I think it's done.

**Comment by AtomicBlom** [comment]
Lol, are you REALLY sure you want me to translate into Australian @mezz? The translation I did for Amadornes was mostly a joke and I expect a bit of backlash over it at some point XD

**Comment by mezz** [comment]
Hmm. Can you refer someone more trustworthy to do the translation? :D

**Comment by ttofis** [comment]
I will do it for sure! Happy to help mezz!

**Comment by ttofis** [comment]
Just as a heads up though, all characters in my language are UTF-8 strictly. So be careful to not open them as ascii as it will be destroyed.

**Comment by AtomicBlom** [comment]
@ELChris414 I did end up doing an Australian translation, without the upside down characters >.>

**Comment by mezz** [comment]
Thanks. That's no problem, there are several translations with special characters in UTF-8 already and everything is working well.

**Comment by ttofis** [comment]
@AtomicBloom upside down characters? Do they need UTF-8?

**Comment by mezz** [comment]
@AtomicBlom I think he quoted that by accident because he was replying by email. His language is Greek.

**Comment by AtomicBlom** [comment]
Oh right, my bad, sorry.

**Comment by XiNiHa** [comment]
Oh I completely forgot about watching Github for a long time... I'll do this

**Comment by DaDodger** [comment]
Hello @mezz, 

I'm the Brazilian translator. Could you please add my name at translators list? Thanks in advance!

**Comment by ghost** [comment]
Hello @mezz,

I'm the Brazilian translator. Could you please add my name at translators list? Thanks in advance!

**pt_BR** PRs: #1229 #1228 #1220

**Comment by mezz** [comment]
Sure, thanks.

**Comment by ttofis** [comment]
This issue has been closed, but if I ever get time it's ok to update the greek translation right?

**Comment by mezz** [comment]
Yes, please feel free to contribute updated translations.
The goal of this issue was just to get translation started and I think it has succeeded at that.
