### ISSUE TITLE
1.11 TODO

### ISSUE THREAD

**Issue by mezz** [mezz/JustEnoughItems#554]
- [x] Change ModID to lowercase
- [x] Allow chat messages up to 256 characters for vanilla server /give command
- [x] Make `IIngredients` support rotating outputs (`List<List<>>`). 
  - [ ] Add example for input->output transformation recipes, that can be restricted by the recipe focus

**Comment by 3TUSK** [comment]
Just curious: any actual usage or demand of rotating outputs?

**Comment by mezz** [comment]
There are some cases like chisel that have one item in and a choice of many different outputs. Not common but it does exist.

**Comment by 3TUSK** [comment]
Ah I see. My mind was bounded within oredict just now...
